Controllers/Home/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAMsUNFWebApplication.Models;
using MySql.Data.MySqlClient;
using System.Configuration;
using SAMsUNFWebApplication.Models.DataAccess;

namespace SAMsUNFWebApplication.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /User/
        public ActionResult Index()
        {
            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> Login(Profile model, string actionRequest)
        {

            if (model.user_name != null && model.user_name.Length > 0 && model.password != null && model.password.Length > 0)
            {
                using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
                {
                    await connection.OpenAsync();

                    model = await new UserRepository(connection).LoginValidation(model.user_name, model.password);

             
                }
                if (model == null)
                {
                    ModelState.AddModelError(string.Empty, "UserId or Password is invalid,please retry.");
                }
                else
                {
                    return RedirectToAction("Dashboard", "Dashboard");
                }
            }
                return View(model);
        }
    }
}

Controllers/OfficeVisit/AddOfficeVisitController.cs
using MySql.Data.MySqlClient;
using SAMsUNFWebApplication.Models;
using SAMsUNFWebApplication.Models.DataAccess;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMsUNFWebApplication.Controllers.OfficeVisit
{
    public class AddOfficeVisitController : Controller
    {
        // GET: AddOfficeVisit
        public async System.Threading.Tasks.Task<ActionResult> AddOfficeVisit()
        {
     
            OfficeVisitCollection coll = new OfficeVisitCollection();
           
            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                await connection.OpenAsync();

                var result = new StudentRepository(connection).GetStudents();
                var result2 = new ContactRepository(connection).GetContacts();
                var result3 = new ContentCourseRepository(connection).GetContentCourses();
                var result4 = new CodeOfConductViolationRepository(connection).GetCodeOfConductViolations();
                var result5 = new HomeRoomRepository(connection).GetHomeRooms();
                var result6 = new RemedialActionRepository(connection).GetRemedialActions();


                coll.allStudents =  (IEnumerable<Student>) result.Result.ToArray();
                coll.allReporters = coll.allHandledBys = (IEnumerable<Models.Contact>)result2.Result.ToArray();
                coll.allLocations = (IEnumerable<Models.ContentCourse>)result3.Result.ToArray();
                coll.allCodeViolations = (IEnumerable<Models.CodeOfConductViolation>)result4.Result.ToArray();
                coll.allHomeRooms = (IEnumerable<Models.HomeRoom>)result5.Result.ToArray();
                coll.allRemedials = (IEnumerable<Models.RemedialAction>)result6.Result.ToArray();
            }

            return View(coll);
        }

        public ActionResult AddVisit(OfficeVisitCollection model, string actionRequest)
        {

            return RedirectToAction("OfficeVisit", "OfficeVisit");
        }
    }
}

Controllers/Training/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAMsUNFWebApplication.Models;
using MySql.Data.MySqlClient;
using System.Configuration;
using SAMsUNFWebApplication.Models.DataAccess;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Text;

namespace SAMsUNFWebApplication.Controllers.Training
{
    public class TrainingController : Controller
    {
        // GET: Training
        public ActionResult Training()
        {
            return View();
        }
     }
}

Views/Shared/AddOfficeVisit.cshtml
@model  SAMsUNFWebApplication.Models.OfficeVisitCollection
@{
    ViewBag.Title = "AddStudent";
 }

<head>
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />

</head>
<table>
    <tr>
        <td colspan="2" align="center" height="30px" style='padding-top:20px;padding-bottom:20px;'>
            <h3 style="color:#255694; font-size:x-large; ">Add A Visit</h3>
        </td>
    </tr>
    <tr>
        <td>
            <div>
                @using (Html.BeginForm("AddVisit", "AddOfficeVisit"))
                {
                    @Html.Label("Select A Student:")
                    @Html.DropDownListFor(m => m.officeVisit.student_id,
                    new SelectList(Model.allStudents,
                                   "student_id", "student_name",
                                   Model.allStudents.First().student_name))
                    <br />
                    @Html.Label("Select A Home Room:")
                    @Html.DropDownListFor(m => m.allHomeRooms,
                    new SelectList(Model.allHomeRooms,
                                   "homeroom_id", "homeroom_name",
                                   "select"))
                    <br />

                    @Html.Label("Select A Reporter:")
                    @Html.DropDownListFor(m => m.allReporters,
                    new SelectList(Model.allReporters,
                                   "contact_id", "contact_name",
                                   Model.allReporters.First().contact_name))
                    <br />
                    @Html.Label("Select Location:")

                    @Html.DropDownListFor(m => m.allLocations,
                    new SelectList(Model.allLocations,
                                   "content_course_id", "name",
                                   Model.allLocations.First().name))
                    <br />
                    @Html.Label("Select Violation:")
                    @Html.DropDownListFor(m => m.allCodeViolations,
                    new SelectList(Model.allCodeViolations,
                                   "code_of_conduct_violation_id", "name",
                                   Model.allCodeViolations.First().name))
                    <br />
                    @Html.Label("Select Remedial Action:")
                    @Html.DropDownListFor(m => m.allRemedials,
                    new SelectList(Model.allRemedials,
                                   "remedial_action_id", "name",
                                   Model.allRemedials.First().name))
                    <br />
                    @Html.Label("Nap?")
                    @Html.CheckBoxFor(m => m.officeVisit.nap)
                    <br />
                    @Html.Label("Comments;")
                    @Html.TextAreaFor(m => m.officeVisit.comments, 5, 55, null)
                    <br />
                    <br />

                    @Html.Label("Handled By:")
                    @Html.DropDownListFor(m => m.allHandledBys,
                    new SelectList(Model.allHandledBys,
                                   "contact_id", "contact_name",
                                   Model.allHandledBys.First().contact_name))

                    <input id="submit" type="submit" value="Add" style="padding-left:20px;" />
                    <input id="submit" type="submit" value="Cancel" />
                }
            </div>
        </td>
    </tr>
    </table>

Views/Shared/_AjaxGridPager.cshtml
@model GridMvc.Site.Models.Grids.AjaxGridPager
@if (!Model.HasPages)
{
    return;
}
<div class="grid-ajax-pager">
    <a href="javascript:void(0);">Show more</a>
</div>

<script>
    (function ($) {
        var self = this;
        this.currentPage = 1;

        var pageLink = $(".grid-ajax-pager a");
        var gridTableBody = pageLink.closest(".grid-wrap").find("tbody");

        pageLink.on("click", function () {
            self.loadNextPage();
        });

        this.loadNextPage = function () {
            self.currentPage++;

            $.get("/Home/GetOrdersGridRows" + self.pad(location.search) + self.currentPage)
                .done(function (response) {

                    gridTableBody.append(response.Html);
                    if (!response.HasItems)
                        pageLink.hide();
                })
                .fail(function () {
                    alert("cannot load items");
                });
        };

        this.pad = function (query) {
            if (query.length == 0) return "?page=";
            return query + "&page=";
        };
    })(jQuery);
</script>

Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title-Student Action Management System</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Layout.css" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" type="text/css" />
    

    
    <script src="~/Scripts/modernizr-2.6.2.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" type-="text/javacript"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")" type="text/javascript"> </script>


</head>

<body>

    <table style="width:1000px;">

        <tr>
            <td>

                <div class="navbar navbar-inverse navbar-fixed-top" style='background-color:#60A2D7;'>
                    <div class="container">
                        <h1 style="color:#FEDA00; font-size:xx-large;">Student Action Management System (SAMs)</h1>
                        @*<div class="navbar-header">

                            <button type="button" class="navbar-toggle" , data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            @Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Dashboard", "Dashboard", "Dashboard", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Create Incident", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Update Incident", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Search For Incident", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            @Html.ActionLink("Reports", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                        </div>*@
                    </div>
                </div>
            </td>
        </tr>
        <tr style="height:400px;">
            <td width="20%" valign="top">
                @Html.Partial("_SideMenu")
            </td>
           
            <td  width="80%" valign="top">
                <div class="container body-content">
                    @RenderBody()
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="center">
                    <footer>
                        <p style="align-items:center;">&copy; @DateTime.Now.Year - Heptad Assembly Test Project</p>
                    </footer>
            </td>
        </tr>
    </table>

</body>
</html>

Views/Shared/_Login.cshtml
@model  SAMsUNFWebApplication.Models.Profile
    @using (Html.BeginForm("Login", "Login"))
            {
        <div style="text-align:right;">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <label>User Id:</label> @Html.TextBoxFor(m => m.UserID)
            @Html.ValidationMessageFor(m => m.UserID, "", new { @class = "text-danger" })
            <label>Password:</label> @Html.PasswordFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
            <input id="submit" type="submit" value="Login"  />
        </div>
    }

Views/Shared/_SideMenu.cshtml
<link href="@Url.Content("~/Content/accordion.css")" type="text/css" rel="stylesheet" />
<script src="~/Scripts/accordion.js" type="text/javascript"></script>

<div id="accordian">
    <ul>
        <li>
            <h3>@Html.ActionLink("Login", "Login", "Login", null, new { @style = "color:white" })</h3>
        </li>
        <li>
            <h3>@Html.ActionLink("Dashboard", "Dashboard", "Dashboard", null, new { @style = "color:white" })</h3>
        </li>
        <li>
            <h3>@Html.ActionLink("Office Visit", "OfficeVisit", "OfficeVisit", null, new { @style = "color:white" })</h3>
        </li>
        <li>
            <h3>Admin Management</h3>
            <ul>
                <li>@Html.ActionLink("Student", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("School", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("School Year", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Grade", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Homeroom", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Contact")</li>
                <li>@Html.ActionLink("Profile", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Office Visit", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Code of Conduct", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Remedial Action", "CodeOfConductViolation", "CodeOfConductViolation")</li>
                <li>@Html.ActionLink("Settings", "CodeOfConductViolation", "CodeOfConductViolation")</li>
            </ul>
        </li>
        <li>
            <h3>Training</h3>
            <ul>
                <li>@Html.ActionLink("Administrator Training", "Training", "Training")</li>
                <li>@Html.ActionLink("Technical Training", "Training", "Training")</li>
            </ul>
        </li>
    </ul>
</div>