SAMsUNFWebApplication/Models/SchoolYear.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SAMsUNFWebApplication.Models
{
    public class SchoolYear
    {
        public int school_year_id { get; set; }
        public bool is_current { get; set; }
        public int last_update_contact_id { get; set; }
        public DateTime last_update_dt { get; set; }
        public DateTime create_dt { get; set; }
        public int create_contact_id { get; set; }
    }

    public class SchoolYearCollection
    {
        public SchoolYear schoolyear { get; set; }
        public IEnumerable<SchoolYear> allSchoolYears { get; set; }
    }
}

SAMsUNFWebApplication/Controllers/SchoolYear/SchoolYearController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAMsUNFWebApplication.Models;
using MySql.Data.MySqlClient;
using System.Configuration;
using SAMsUNFWebApplication.Models.DataAccess;
using System.IO;
using Dapper;

namespace SAMsUNFWebApplication.Controllers.CodeOfConductViolation
{
    public class SchoolYearController : Controller
    {
        [Authorize]
        // GET: SchoolYear
        public async System.Threading.Tasks.Task<ActionResult> SchoolYear()
        {
            SchoolYearCollection coll = new SchoolYearCollection();

            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                await connection.OpenAsync();
                var result = new SchoolYearRepository(connection).GetSchoolYears();
                coll.allSchoolYears = (IEnumerable<Models.SchoolYear>)result.Result.ToArray();
            }
            return View(coll);
        }

        public System.Web.Mvc.RedirectResult SetSchoolYear(string allSchoolYears)
        {
            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                var result = new SchoolYearRepository(connection).SetSchoolYear(allSchoolYears);
                if (result == "success")
                {
                    return Redirect("SchoolYear/?error=fileloaded");
                }
                else
                {
                    //do something else here.
                    return Redirect("SchoolYear/?error=invalidfile");
                }
            }
        }

    }
}

SAMsUNFWebApplication/Views/SchoolYear/SchoolYear.cshtml
@model  SAMsUNFWebApplication.Models.SchoolYearCollection
@{
    ViewBag.Title = "SetSchoolYear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<head>
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Style.css")" rel="stylesheet" />

</head>*@
<div>
    @if (Request.Params["error"] == "invalidfile")
    {
        <div class="bg-danger">The modifications for school year did not work due to a system error.  Please try again.</div>

    }
    @if (Request.Params["error"] == "fileloaded")
    {
        <div class="bg-success">The school year was modified successfully.</div>

    }
</div>
<table class="table" style="width:0%">
    <tr>
        <td align="left" valign="bottom">
            <div style="float: left;">
                <h3 class="viewname-h3">School Year</h3>
            </div>
        </td>


    </tr>
    <tr>
        <td>
            <div>
                @using (Html.BeginForm("SetSchoolYear", "SchoolYear", FormMethod.Get))
                {
                    //TxtFirstName, string TxtLastName, string TxtSchool, string TxtGrade, string TxtGender, string TxtHomeroom
                    <table class="table">
                        <tbody>
                            <tr>
                                <td>
                                    @Html.Label("Select School Year:")
                                </td>
                                <td>

                                    @Html.DropDownListFor(m => m.allSchoolYears,
                                        new SelectList(Model.allSchoolYears,
                                   "school_year_id", "school_year_id",
                                   Model.allSchoolYears.First().school_year_id),
                                        new
                                        {
                                            @class = "form-control"
                                        })
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" align="right">
                                    <input id="submit" class="btn btn-primary" type="submit" value="Add" style="padding-left:20px;" />
                                    <button class="btn btn-info" onclick="history.go(-1)">Cancel</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }

            </div>

        </td>
    </tr>
</table>