SAMsUNFWebApplication/Models/School.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMsUNFWebApplication.Models
{
    public class School
    {
        public int school_id { get; set; }
        public string name { get; set; }
    }

    public class SchoolCollection
    {
        public School school { get; set; }
        public IEnumerable<School> allSchools { get; set; }
        public IEnumerable<School> singleSchool { get; set; }
        public SelectList schoolselectlist { get; set; }
    }
}

SAMsUNFWebApplication/Controllers/School/EditSchoolController.cs
using MySql.Data.MySqlClient;
using SAMsUNFWebApplication.Models;
using SAMsUNFWebApplication.Models.DataAccess;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SAMsUNFWebApplication.Controllers.School
{
    public class EditSchoolController : Controller
    {
        [Authorize]
        // GET: EditSchool
        public ActionResult Index()
        {
            return View();
        }
        public async System.Threading.Tasks.Task<ActionResult> EditSchool(string id)
        {

            SchoolCollection coll = new SchoolCollection();

            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                await connection.OpenAsync();
                var result = new SchoolRepository(connection).GetSchool(id);
                var result2 = new SchoolRepository(connection).GetSchools();

                coll.singleSchool = (IEnumerable<Models.School>)result.Result.ToArray();
                coll.allSchools = (IEnumerable<Models.School>)result2.Result.ToArray();
                coll.schoolselectlist = new SelectList(result2.Result.ToList(), "school_id", "name", new { id = "SchoolID", @required = "required" });
            }

            return View(coll);
        }
    }
}

SAMsUNFWebApplication/Controllers/School/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SAMsUNFWebApplication.Models;
using MySql.Data.MySqlClient;
using System.Configuration;
using SAMsUNFWebApplication.Models.DataAccess;
using System.IO;
using Dapper;

namespace SAMsUNFWebApplication.Controllers.School
{
    public class SchoolController : Controller
    {
        [Authorize]
        // GET: School
        public ActionResult Index()
        {
            return View();
        }
        public async System.Threading.Tasks.Task<ActionResult> School()
        {
            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                await connection.OpenAsync();
                var result = await new SchoolRepository(connection).GetSchools();
                return View(result);
            }
        }
        public async System.Threading.Tasks.Task<ActionResult> GetSchool(string id)
        {
            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                await connection.OpenAsync();
                var result = await new SchoolRepository(connection).GetSchool(id);
                return View(result);
            }
        }
        public System.Web.Mvc.RedirectResult CreateSchool(string SchoolName)
        {
            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                var result = new SchoolRepository(connection).CreateSchool(SchoolName);
                if (result == "success")
                {
                    return Redirect("School/School/?error=fileloaded");
                }
                else
                {
                    //do something else here.
                    return Redirect("School/School/?error=invalidfile");
                }
            }
        }

        public System.Web.Mvc.RedirectResult EditSchool(string SchoolID, string SchoolName)
        {
            using (var connection = new MySqlConnection(ConfigurationManager.ConnectionStrings[Constants.ConnectionStringName].ConnectionString))
            {
                var result = new SchoolRepository(connection).EditSchool(SchoolID, SchoolName);
                if (result == "success")
                {
                    return Redirect("School/School/?error=fileloaded");
                }
                else
                {
                    //do something else here.
                    return Redirect("School/School/?error=invalidfile");
                }
            }
        }
    }
}

SAMsUNFWebApplication/Views/School/School.cshtml
@model  IEnumerable<SAMsUNFWebApplication.Models.School>
@using GridMvc.Html
@{
    ViewBag.Title = "School";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<head>
    <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/gridmvc.datepicker.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap-datepicker.js")"></script>

</head>*@
<div>
    @if (Request.Params["error"] == "invalidfile")
    {
        <div class="bg-danger">The modifications for school did not work due to a system error.  Please try again.</div>

    }
    @if (Request.Params["error"] == "fileloaded")
    {
        <div class="bg-success">The school was modified successfully.</div>

    }
</div>
<table class="table" style="width:0%">
    <tr>
        <td align="left" valign="bottom">
            <div style="float: left;">
                <h3 class="viewname-h3">School</h3>
            </div>
        </td>
      
           
    </tr>
    <tr>
        <td align="center" style="padding-left:0px;">

            <div style="width:500px; text-align:center;">
                <div style="float: left;margin-top:20px;">
                    @Html.ActionLink("Add School", "CreateSchool", "Home", null, new { @class = "btn btn-info" })
                </div>

                @Html.Grid(Model).Columns(columns =>
{
columns.Add()
.Encoded(false)
.Sanitized(false)
.SetWidth(30)
.RenderValueAs(d =>
                    @<b>
                        @Html.ActionLink("Edit", "EditSchool", "EditSchool",
               new
               {
                   @id = d.school_id
               },
               new
               {
                   @class = "btn btn-default"
               })
                    </b>);
    columns.Add(c => c.name).Titled("Name").SetWidth(15);
}).WithPaging(10).Sortable(true).Filterable(true)
            </div>
        </td>
    </tr>
</table>